import { SkillUpCourse } from '../types';

export const SKILLUP_COURSES: SkillUpCourse[] = [
  // --- GOOGLE ---
  {
    id: 'skillup-google-cloud-foundations',
    title: 'Google Cloud Computing Foundations Certificate',
    provider: 'Google',
    domain: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: '24 Hours (Self-Paced)',
    credentialType: 'Free Digital Badge',
    rating: 4.8,
    studentsEnrolled: '850K+',
    description: 'Learn foundational cloud technology concepts directly from Google engineers. Covers Google Cloud Platform (GCP) compute, BigQuery data warehousing, VPC networking, security primitives, and IAM role management.',
    skillsLearned: ['Compute Engine (VMs)', 'Google Kubernetes Engine (GKE)', 'BigQuery & Dataflow', 'IAM & Cloud Armor Security', 'VPC Peering'],
    courseUrl: 'https://www.cloudskillsboost.google/course_templates/153',
    prerequisites: 'Basic understanding of IT and computing concepts.',
    highlightNote: 'Official Google Cloud Skills Boost Badge with Credly Digital Credential.'
  },
  {
    id: 'skillup-google-cybersecurity',
    title: 'Google Cybersecurity Professional Certificate',
    provider: 'Google',
    domain: 'Cybersecurity',
    difficulty: 'Beginner',
    duration: '6 Months (7 hrs/week)',
    credentialType: 'Free Verified Certificate',
    rating: 4.9,
    studentsEnrolled: '1.4M+',
    description: 'Developed by Google security experts to prepare learners for entry-level cybersecurity roles. Covers SIEM tools (Chronicle, Splunk), Linux command line, SQL injection detection, IDS/IPS, Python automation, and incident mitigation.',
    skillsLearned: ['SIEM & Packet Sniffing (Wireshark)', 'Linux Bash & Shell Hardening', 'Python for Security Automation', 'NIST Cybersecurity Framework', 'SQL Database Auditing'],
    courseUrl: 'https://grow.google/certificates/cybersecurity/',
    prerequisites: 'No previous experience required.',
    highlightNote: 'Free audit available; eligible for 100% free scholarships via Google Career Certificates program.'
  },
  {
    id: 'skillup-google-ga4-analytics',
    title: 'Google Analytics 4 (GA4) Official Certification',
    provider: 'Google',
    domain: 'Data Science',
    difficulty: 'Intermediate',
    duration: '12 Hours',
    credentialType: 'Free Verified Certificate',
    rating: 4.7,
    studentsEnrolled: '2.1M+',
    description: 'Official Google Skillshop accreditation validating ability to set up GA4 properties, structure event-based data schemas, build predictive audiences, and integrate analytics with BigQuery.',
    skillsLearned: ['Event-Driven Data Models', 'GA4 Measurement Protocol', 'BigQuery Export Streaming', 'Conversion Funnel Analysis', 'Attribution Modeling'],
    courseUrl: 'https://skillshop.withgoogle.com/',
    prerequisites: 'Foundational web tracking or digital product knowledge.',
    highlightNote: '100% Free Official Certificate directly issued by Google Skillshop with verifiable URL.'
  },
  {
    id: 'skillup-google-android-compose',
    title: 'Android Basics with Jetpack Compose',
    provider: 'Google',
    domain: 'Software Engineering',
    difficulty: 'Beginner',
    duration: '40 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.9,
    studentsEnrolled: '620K+',
    description: 'Learn modern Android application development from Google Developer Training team. Write idiomatic Kotlin code, build declarative UIs with Jetpack Compose, handle Coroutines asynchronous flow, and connect to REST APIs.',
    skillsLearned: ['Kotlin 2.0 Coroutines', 'Jetpack Compose Declarative UI', 'ViewModel & State Hoisting', 'Room SQLite Database', 'Retrofit Network Calls'],
    courseUrl: 'https://developer.android.com/courses/android-basics-compose/course',
    prerequisites: 'Basic programming fundamentals in any object-oriented language.',
    highlightNote: 'Earn official Google Developers profile badges and shareable portfolio code.'
  },
  {
    id: 'skillup-google-ai-kaggle',
    title: 'Kaggle Machine Learning & Deep Learning Micro-Degrees',
    provider: 'Google',
    domain: 'AI & Machine Learning',
    difficulty: 'Intermediate',
    duration: '16 Hours',
    credentialType: 'Free Verified Certificate',
    rating: 4.9,
    studentsEnrolled: '3.5M+',
    description: 'Fast-paced, hands-on micro-courses created by Google Kaggle data scientists. Covers Pandas manipulation, Random Forests, XGBoost, Deep Learning with TensorFlow/Keras, and Computer Vision.',
    skillsLearned: ['Pandas & NumPy Vectorization', 'Feature Engineering', 'XGBoost & Gradient Boosting', 'TensorFlow 2 & CNNs', 'Model Evaluation & AUC-ROC'],
    courseUrl: 'https://www.kaggle.com/learn',
    prerequisites: 'Basic Python syntax.',
    highlightNote: '100% Free Certificates of Completion awarded for each completed Kaggle track.'
  },

  // --- MICROSOFT ---
  {
    id: 'skillup-ms-az900',
    title: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    provider: 'Microsoft',
    domain: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: '18 Hours',
    credentialType: 'Accredited Exam Path',
    rating: 4.8,
    studentsEnrolled: '2.8M+',
    description: 'Official Microsoft Learn comprehensive curriculum covering Azure architecture, compute, networking, storage, Azure Active Directory / Entra ID, security postures, SLA guarantees, and cloud governance.',
    skillsLearned: ['Azure Virtual Machines & App Services', 'Blob Storage & Cosmos DB', 'Entra ID (Azure AD) & RBAC', 'Azure Policy & Blueprints', 'Cloud Cost Management'],
    courseUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/',
    prerequisites: 'General interest in cloud infrastructure.',
    highlightNote: 'Free official learning paths + free exam vouchers through Microsoft Virtual Training Days & Student Pack.'
  },
  {
    id: 'skillup-ms-generative-ai',
    title: 'Career Essentials in Generative AI by Microsoft and LinkedIn',
    provider: 'Microsoft',
    domain: 'AI & Machine Learning',
    difficulty: 'Beginner',
    duration: '6 Hours',
    credentialType: 'Free Verified Certificate',
    rating: 4.9,
    studentsEnrolled: '950K+',
    description: 'Developed jointly by Microsoft and LinkedIn to equip professionals with generative AI fluency. Explores foundational LLM architectures, prompt engineering, Microsoft Copilot integration, ethics, and workplace automation.',
    skillsLearned: ['Large Language Models (LLMs)', 'Prompt Engineering Patterns', 'Microsoft 365 Copilot', 'Responsible AI Frameworks', 'Generative Search & Bing AI'],
    courseUrl: 'https://www.linkedin.com/learning/paths/career-essentials-in-generative-ai-by-microsoft-and-linkedin',
    prerequisites: 'No technical prerequisites.',
    highlightNote: '100% Free Certificate of Completion and LinkedIn credential badge.'
  },
  {
    id: 'skillup-ms-github-foundations',
    title: 'GitHub Foundations & Open Source Collaboration',
    provider: 'Microsoft',
    domain: 'DevOps & Systems',
    difficulty: 'Beginner',
    duration: '14 Hours',
    credentialType: 'Accredited Exam Path',
    rating: 4.8,
    studentsEnrolled: '500K+',
    description: 'Master version control, Git branching strategies, pull request workflows, GitHub Actions CI/CD automation, GitHub Projects kanban management, and Dependabot supply-chain security.',
    skillsLearned: ['Git Internals & Branching (Trunk-Based)', 'GitHub Actions CI/CD Workflows', 'Pull Request Review Etiquette', 'Dependabot & Secret Scanning', 'GitHub Packages & Releases'],
    courseUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/github-foundations/',
    prerequisites: 'Familiarity with basic terminal commands.',
    highlightNote: 'Official Microsoft Learn interactive sandbox labs with free student examination options.'
  },
  {
    id: 'skillup-ms-pl300-powerbi',
    title: 'Microsoft Power BI Data Analyst (PL-300)',
    provider: 'Microsoft',
    domain: 'Data Science',
    difficulty: 'Intermediate',
    duration: '26 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.7,
    studentsEnrolled: '1.1M+',
    description: 'Comprehensive data modeling and business intelligence series on Microsoft Learn. Prepare, model, and visualize data using Power Query, DAX formulas, star schema modeling, and row-level security (RLS).',
    skillsLearned: ['Power Query ETL', 'DAX (Data Analysis Expressions)', 'Star Schema Data Modeling', 'Interactive Dashboards & KPI Cards', 'Row-Level Security (RLS)'],
    courseUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/power-bi-data-analyst-associate/',
    prerequisites: 'Basic familiarity with spreadsheets and SQL.',
    highlightNote: 'Includes official Microsoft Applied Skills verifiable credentials upon lab completion.'
  },

  // --- IBM ---
  {
    id: 'skillup-ibm-cybersecurity',
    title: 'IBM Cybersecurity Fundamentals Professional Certificate',
    provider: 'IBM',
    domain: 'Cybersecurity',
    difficulty: 'Beginner',
    duration: '30 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.8,
    studentsEnrolled: '680K+',
    description: 'Offered via IBM SkillsBuild. Dive into enterprise threat vectors, penetration testing methodologies, cryptography (AES, RSA, SHA-256), digital forensics, identity management, and IBM QRadar SIEM architecture.',
    skillsLearned: ['Enterprise Penetration Testing', 'Symmetric & Asymmetric Cryptography', 'IBM QRadar SIEM & Log Analysis', 'Zero Trust Architecture', 'Incident Response Playbooks'],
    courseUrl: 'https://skillsbuild.org/students',
    prerequisites: 'Basic computer hardware and networking knowledge.',
    highlightNote: '100% Free Official IBM Digital Badge verifiable worldwide on Credly.'
  },
  {
    id: 'skillup-ibm-deep-learning',
    title: 'Deep Learning with TensorFlow & Python',
    provider: 'IBM',
    domain: 'AI & Machine Learning',
    difficulty: 'Advanced',
    duration: '20 Hours',
    credentialType: 'Free Verified Certificate',
    rating: 4.8,
    studentsEnrolled: '420K+',
    description: 'Provided by IBM Cognitive Class. Master artificial neural networks, backpropagation calculus, Convolutional Neural Networks (CNNs) for image classification, Recurrent Neural Networks (RNNs) for sequential text, and autoencoders.',
    skillsLearned: ['Backpropagation & Loss Optimization', 'TensorFlow 2.x & Keras Functional API', 'Convolutional Networks (ResNet)', 'LSTMs & Attention Mechanisms', 'Model Deployment with TF Serving'],
    courseUrl: 'https://cognitiveclass.ai/courses/deep-learning-tensorflow',
    prerequisites: 'Proficiency in Python and multivariable calculus/linear algebra.',
    highlightNote: '100% Free Verified Certificate of Achievement and IBM Cognitive Class badge.'
  },
  {
    id: 'skillup-ibm-data-science',
    title: 'IBM Data Science Foundations',
    provider: 'IBM',
    domain: 'Data Science',
    difficulty: 'Beginner',
    duration: '18 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.7,
    studentsEnrolled: '910K+',
    description: 'Learn the complete data science lifecycle from hypothesis generation to data scraping, exploratory data analysis with Jupyter Notebooks, statistical modeling, and relational database querying with DB2/PostgreSQL.',
    skillsLearned: ['Jupyter Notebooks & Python Data Science', 'Exploratory Data Analysis (EDA)', 'Statistical Inference & Hypothesis Testing', 'Relational SQL Query Optimization', 'Matplotlib & Seaborn Visualizations'],
    courseUrl: 'https://cognitiveclass.ai/courses/data-science-101',
    prerequisites: 'No prior programming experience required.',
    highlightNote: 'Free IBM badge issued on Credly with verifiable QR code.'
  },

  // --- AMAZON WEB SERVICES (AWS) ---
  {
    id: 'skillup-aws-cloud-practitioner',
    title: 'AWS Cloud Practitioner Essentials',
    provider: 'AWS',
    domain: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: '10 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.8,
    studentsEnrolled: '2.3M+',
    description: 'The official free curriculum created by AWS technical instructors. Covers AWS global infrastructure (Regions, AZs, Edge Locations), Amazon EC2, Amazon S3, AWS Lambda serverless compute, Amazon RDS, and AWS Well-Architected Framework.',
    skillsLearned: ['Amazon EC2 & Auto Scaling', 'Amazon S3 Object Storage & Lifecycle', 'AWS Lambda Serverless Functions', 'VPC Subnets & Security Groups', 'AWS Cost Explorer & Pricing Calculators'],
    courseUrl: 'https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/',
    prerequisites: 'General IT comprehension.',
    highlightNote: '100% Free Official Course on AWS Skill Builder with AWS Digital Badge.'
  },
  {
    id: 'skillup-aws-educate-ml',
    title: 'AWS Educate Machine Learning Foundations',
    provider: 'AWS',
    domain: 'AI & Machine Learning',
    difficulty: 'Intermediate',
    duration: '15 Hours',
    credentialType: 'Free Digital Badge',
    rating: 4.7,
    studentsEnrolled: '380K+',
    description: 'Designed exclusively for students and self-taught developers. Learn how to train and deploy machine learning models using Amazon SageMaker, AWS Rekognition for computer vision, Amazon Comprehend for NLP, and AWS Polly.',
    skillsLearned: ['Amazon SageMaker Studio', 'Computer Vision via AWS Rekognition', 'NLP with Amazon Comprehend', 'ML Pipeline Monitoring', 'Feature Store Engineering'],
    courseUrl: 'https://aws.amazon.com/education/awseducate/',
    prerequisites: 'Basic Python syntax and understanding of statistics.',
    highlightNote: 'Free for students with no credit card required; earns official AWS Educate Credly badge.'
  },

  // --- META ---
  {
    id: 'skillup-meta-frontend',
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Meta',
    domain: 'Software Engineering',
    difficulty: 'Beginner',
    duration: '7 Months (6 hrs/week)',
    credentialType: 'Specialization Audit',
    rating: 4.8,
    studentsEnrolled: '900K+',
    description: 'Taught by engineers at Meta (Facebook/Instagram). Learn semantic HTML5, modern responsive CSS, JavaScript ES6+, React, component state architecture, client-side routing, Jest unit testing, and portfolio deployment.',
    skillsLearned: ['Modern React 18+ & Hooks', 'Responsive UI & CSS Grid/Flexbox', 'State Management & Context API', 'Jest & React Testing Library', 'Git Version Control & Figma Handoff'],
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    prerequisites: 'No prior coding experience.',
    highlightNote: 'All curriculum materials and video lectures are 100% free via the Coursera Audit option.'
  },

  // --- CISCO & LINUX FOUNDATION & HARVARD ---
  {
    id: 'skillup-cisco-cyber-essentials',
    title: 'Cisco Networking Academy: Cybersecurity Essentials',
    provider: 'Cisco',
    domain: 'Cybersecurity',
    difficulty: 'Beginner',
    duration: '30 Hours',
    credentialType: 'Free Verified Certificate',
    rating: 4.9,
    studentsEnrolled: '1.7M+',
    description: 'Offered worldwide through Cisco Networking Academy (Skills for All). Master network packet structures (TCP/IP), firewall packet filters, intrusion prevention systems, threat taxonomy, and Cisco defense architecture.',
    skillsLearned: ['TCP/IP Protocol Stack Internals', 'Firewalls & DMZ Architectures', 'Malware Analysis & Threat Vectoring', 'Cisco Packet Tracer Simulations', 'Security Operations Center (SOC) Workflows'],
    courseUrl: 'https://www.netacad.com/courses/cybersecurity/cybersecurity-essentials',
    prerequisites: 'Foundational computer network literacy.',
    highlightNote: '100% Free Official Cisco NetAcad Certificate of Completion and Credly digital badge.'
  },
  {
    id: 'skillup-linux-foundation-lfs101x',
    title: 'Introduction to Linux (LFS101x)',
    provider: 'Linux Foundation',
    domain: 'DevOps & Systems',
    difficulty: 'Beginner',
    duration: '40 Hours',
    credentialType: 'Specialization Audit',
    rating: 4.8,
    studentsEnrolled: '1.5M+',
    description: 'Authored by Linus Torvalds\' organization, the Linux Foundation. Covers command-line mastery, filesystem hierarchy standard (FHS), process signals, Bash shell scripting, user privilege administration, and system service management.',
    skillsLearned: ['Linux Bash Shell Mastery', 'Filesystem Permissions & chmod/chown', 'Process Management (ps, top, kill)', 'Systemd Service Administration', 'Package Managers (apt, dnf)'],
    courseUrl: 'https://www.edx.org/learn/linux/the-linux-foundation-introduction-to-linux',
    prerequisites: 'Basic computer operation.',
    highlightNote: '100% Free Access provided directly by The Linux Foundation on edX.'
  },
  {
    id: 'skillup-harvard-cs50',
    title: 'Harvard CS50: Introduction to Computer Science',
    provider: 'Harvard',
    domain: 'Software Engineering',
    difficulty: 'Intermediate',
    duration: '12 Weeks (8 hrs/week)',
    credentialType: 'Free Verified Certificate',
    rating: 4.9,
    studentsEnrolled: '5.2M+',
    description: 'The world-famous computer science course taught by David J. Malan at Harvard University. Covers C memory pointers, memory allocators (malloc/free), algorithms (sorting, binary search), Python, SQL, web development, and algorithmic complexity.',
    skillsLearned: ['C Programming & Memory Pointers', 'Data Structures (Hash Tables, Tries)', 'Algorithmic Complexity (Big-O)', 'Python & Flask Backend Services', 'SQL Database Normalization'],
    courseUrl: 'https://cs50.harvard.edu/x/',
    prerequisites: 'Dedication to problem-solving. No prior coding required.',
    highlightNote: '100% Free Verified Certificate of Completion directly from Harvard CS50 with score >= 70%.',
    isPaid: false,
    price: { inr: 0, usd: 0 }
  },

  // --- TOP-TIER PAID COURSES & BOOTCAMPS ---
  {
    id: 'skillup-paid-deeplearning-specialization',
    title: 'Deep Learning Specialization (5-Course Masterclass)',
    provider: 'DeepLearning.AI',
    providerPlatform: 'Coursera',
    domain: 'AI & Machine Learning',
    difficulty: 'Intermediate',
    duration: '3 Months (10 hrs/week)',
    credentialType: 'Paid Professional Certificate',
    rating: 4.9,
    studentsEnrolled: '1.2M+',
    description: 'Taught by AI pioneer Andrew Ng. Master foundational deep learning, train neural networks in Python, build Convolutional Networks for computer vision, Sequence Models for NLP, and explore Transformers architecture.',
    skillsLearned: ['Deep Neural Networks & Backpropagation', 'Convolutional Neural Networks (CNNs)', 'Sequence Models & LSTMs', 'Transformers & Attention Mechanisms', 'Hyperparameter Tuning & Batch Normalization'],
    courseUrl: 'https://www.coursera.org/specializations/deep-learning',
    prerequisites: 'Intermediate Python and linear algebra / calculus basics.',
    highlightNote: 'Includes official shareable credential from DeepLearning.AI, graded programming assignments, and financial aid available.',
    isPaid: true,
    price: {
      inr: 3499,
      usd: 49,
      originalInr: 6999,
      originalUsd: 99,
      discountPercent: 50
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'Neural Networks and Deep Learning', hours: 24, topics: ['Vectorization', 'Activation Functions', 'Gradient Descent'] },
      { moduleNumber: 2, title: 'Improving Deep Neural Networks: Hyperparameter Tuning', hours: 18, topics: ['Regularization', 'Optimization Algorithms', 'TensorFlow'] },
      { moduleNumber: 3, title: 'Structuring Machine Learning Projects', hours: 12, topics: ['Error Analysis', 'Transfer Learning', 'End-to-End Deep Learning'] },
      { moduleNumber: 4, title: 'Convolutional Neural Networks for Computer Vision', hours: 28, topics: ['ResNets', 'YOLO Object Detection', 'Facial Recognition'] },
      { moduleNumber: 5, title: 'Sequence Models & Attention Transformers', hours: 30, topics: ['LSTMs', 'Self-Attention', 'Transformer Encoders/Decoders'] }
    ]
  },
  {
    id: 'skillup-paid-aws-saa-bootcamp',
    title: 'Ultimate AWS Certified Solutions Architect Associate (SAA-C03)',
    provider: 'AWS',
    providerPlatform: 'Udemy',
    domain: 'Cloud Computing',
    difficulty: 'Intermediate',
    duration: '28 Hours (On-Demand Video + 2 Full Practice Tests)',
    credentialType: 'Bootcamp Masterclass',
    rating: 4.8,
    studentsEnrolled: '950K+',
    description: 'The #1 bestselling AWS exam prep masterclass by Stephane Maarek. Covers architectural design principles across IAM, EC2, S3, RDS, DynamoDB, Lambda, VPC networking, CloudFront, Route53, and cost optimization.',
    skillsLearned: ['VPC Peering, Subnets & NAT Gateways', 'Multi-AZ High Availability RDS & Aurora', 'Serverless AWS Lambda & API Gateway', 'S3 Glacier Lifecycle Policies', 'KMS Encryption & CloudWatch Telemetry'],
    courseUrl: 'https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/',
    prerequisites: 'Basic knowledge of IT infrastructure and web networking.',
    highlightNote: 'Includes 2 full-length practice exams with 130 realistic exam questions, slide decks, and lifetime access.',
    isPaid: true,
    price: {
      inr: 549,
      usd: 19.99,
      originalInr: 3499,
      originalUsd: 84.99,
      discountPercent: 84
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'IAM, EC2 Compute & Storage Foundations', hours: 6, topics: ['IAM Roles & Policies', 'EBS Volumes', 'Security Groups'] },
      { moduleNumber: 2, title: 'High Availability & Scalability: ELB & ASG', hours: 5, topics: ['Application Load Balancer', 'Auto Scaling Policies', 'Target Groups'] },
      { moduleNumber: 3, title: 'Databases on AWS: RDS, Aurora & DynamoDB', hours: 5, topics: ['Read Replicas', 'Multi-Region Replication', 'DynamoDB DAX'] },
      { moduleNumber: 4, title: 'VPC Networking & Hybrid Cloud Connectivity', hours: 6, topics: ['CIDR Blocks', 'Transit Gateway', 'VPC Endpoints'] },
      { moduleNumber: 5, title: 'Serverless Solutions: Lambda, SQS & SNS', hours: 6, topics: ['EventBridge', 'Step Functions', 'API Gateway Websockets'] }
    ]
  },
  {
    id: 'skillup-paid-stanford-ml',
    title: 'Stanford Machine Learning Specialization',
    provider: 'Stanford Online',
    providerPlatform: 'Coursera',
    domain: 'AI & Machine Learning',
    difficulty: 'Beginner',
    duration: '2 Months (9 hrs/week)',
    credentialType: 'Paid Professional Certificate',
    rating: 4.9,
    studentsEnrolled: '480K+',
    description: 'Jointly created by Stanford Online and DeepLearning.AI. Delivers a modern re-imagination of Andrew Ng\'s legendary Stanford CS229 curriculum with hands-on NumPy, scikit-learn, and TensorFlow assignments.',
    skillsLearned: ['Supervised Learning (Regression & Classification)', 'Advanced Learning Algorithms (Neural Nets, Decision Trees, XGBoost)', 'Unsupervised Learning (K-Means, PCA, Anomaly Detection)', 'Recommender Systems (Collaborative Filtering)', 'Reinforcement Learning & Q-Learning'],
    courseUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    prerequisites: 'High school math and foundational Python knowledge.',
    highlightNote: 'Official Stanford Online digital certificate of completion with verifiable credential ID.',
    isPaid: true,
    price: {
      inr: 3199,
      usd: 49,
      originalInr: 5999,
      originalUsd: 89,
      discountPercent: 47
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'Supervised Machine Learning: Regression & Classification', hours: 18, topics: ['Cost Functions', 'Gradient Descent', 'Logistic Regression'] },
      { moduleNumber: 2, title: 'Advanced Learning Algorithms', hours: 22, topics: ['Multi-Layer Perceptrons', 'Decision Trees', 'Random Forests', 'XGBoost'] },
      { moduleNumber: 3, title: 'Unsupervised Learning, Recommenders & RL', hours: 20, topics: ['Dimensionality Reduction', 'Matrix Factorization', 'Bellman Equation'] }
    ]
  },
  {
    id: 'skillup-paid-fullstack-react-masterclass',
    title: 'Complete React & Next.js 15 Full Stack Bootcamp (w/ TypeScript)',
    provider: 'Udemy',
    providerPlatform: 'Udemy',
    domain: 'Software Engineering',
    difficulty: 'Intermediate',
    duration: '42 Hours (On-Demand Video + 4 Production Projects)',
    credentialType: 'Bootcamp Masterclass',
    rating: 4.8,
    studentsEnrolled: '420K+',
    description: 'Learn modern React 19, Server Components, Next.js 15 App Router, TypeScript, Tailwind CSS, Prisma ORM, PostgreSQL, and Stripe checkout by building real-world software applications.',
    skillsLearned: ['Next.js 15 Server Components (RSC)', 'TypeScript Generics & Zod Schemas', 'Prisma ORM & PostgreSQL Migrations', 'Stripe Payment Webhooks', 'NextAuth.js v5 Authentication'],
    courseUrl: 'https://www.udemy.com/',
    prerequisites: 'Basic HTML, CSS and foundational JavaScript.',
    highlightNote: 'Includes full source code on GitHub for 4 full-stack apps, automated testing modules, and 30-day refund policy.',
    isPaid: true,
    price: {
      inr: 499,
      usd: 16.99,
      originalInr: 3899,
      originalUsd: 79.99,
      discountPercent: 87
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'React 19 Core & Hooks Mastery', hours: 10, topics: ['useActionState', 'useOptimistic', 'Custom Hooks'] },
      { moduleNumber: 2, title: 'TypeScript for Production React', hours: 8, topics: ['Component Props Typing', 'Generic Handlers', 'Strict TS Config'] },
      { moduleNumber: 3, title: 'Next.js 15 App Router & Server Actions', hours: 12, topics: ['Layouts', 'Caching Strategies', 'Parallel Routes'] },
      { moduleNumber: 4, title: 'Database & Stripe Billing Integration', hours: 12, topics: ['PostgreSQL', 'Prisma Schema', 'Webhook Verification'] }
    ]
  },
  {
    id: 'skillup-paid-cka-kubernetes',
    title: 'Certified Kubernetes Administrator (CKA) with Practice Tests',
    provider: 'Linux Foundation',
    providerPlatform: 'Udemy',
    domain: 'DevOps & Systems',
    difficulty: 'Advanced',
    duration: '22 Hours + 5 Mock Exam Sandboxes',
    credentialType: 'Bootcamp Masterclass',
    rating: 4.9,
    studentsEnrolled: '380K+',
    description: 'Designed to help you pass the official CNCF / Linux Foundation CKA exam on your first attempt. Interactive browser-based terminal sandboxes simulating real exam challenges.',
    skillsLearned: ['etcd Backup and Restoration', 'Cluster Architecture & kubeadm', 'RBAC, ServiceAccounts & TLS Certs', 'CoreDNS & Ingress Controller Setup', 'StorageClasses & PersistentVolumeClaims'],
    courseUrl: 'https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/',
    prerequisites: 'Foundational Linux and container (Docker) experience.',
    highlightNote: 'Over 80 browser-based lab challenges matching the real CNCF exam terminal interface.',
    isPaid: true,
    price: {
      inr: 649,
      usd: 21.99,
      originalInr: 4299,
      originalUsd: 89.99,
      discountPercent: 85
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'Core Concepts & Pod Scheduling', hours: 5, topics: ['Node Affinity', 'Taints & Tolerations', 'Static Pods'] },
      { moduleNumber: 2, title: 'Cluster Maintenance & Logging', hours: 4, topics: ['kubeadm upgrade', 'etcd snapshot save', 'Drain & Cordon'] },
      { moduleNumber: 3, title: 'Security: RBAC & Network Policies', hours: 5, topics: ['Kubeconfig files', 'NetworkPolicy ingress/egress', 'ClusterRoles'] },
      { moduleNumber: 4, title: 'Storage, Services & Troubleshooting', hours: 8, topics: ['PV/PVC Lifecycle', 'CoreDNS debugging', 'Kubelet service logs'] }
    ]
  },
  {
    id: 'skillup-paid-meta-frontend-cert',
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Meta',
    providerPlatform: 'Coursera',
    domain: 'Software Engineering',
    difficulty: 'Beginner',
    duration: '7 Months (6 hrs/week)',
    credentialType: 'Paid Professional Certificate',
    rating: 4.8,
    studentsEnrolled: '460K+',
    description: 'Built by Meta software engineers. Prepares students for entry-level front-end developer positions. Master HTML5, CSS3, UX design in Figma, JavaScript, React, version control with Git, and technical interview prep.',
    skillsLearned: ['React Hooks & Component State', 'Figma UI Wireframing to Responsive Code', 'Unit Testing with Jest & React Testing Library', 'Git Branching & GitHub PR Workflows', 'Front-End Technical Interview Algorithms'],
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    prerequisites: 'No prior coding experience required.',
    highlightNote: 'Grants access to the Meta Career Programs Job Board with exclusive employer partners hiring graduates.',
    isPaid: true,
    price: {
      inr: 2999,
      usd: 49,
      originalInr: 5999,
      originalUsd: 99,
      discountPercent: 50
    },
    enrollmentType: 'paid',
    hasMoneyBackGuarantee: true,
    syllabus: [
      { moduleNumber: 1, title: 'Introduction to Front-End Development', hours: 14, topics: ['Semantic HTML5', 'Responsive CSS3', 'Bootstrap 5'] },
      { moduleNumber: 2, title: 'Programming with JavaScript', hours: 20, topics: ['ES6 Syntax', 'Functional Programming', 'Unit Testing w/ Jest'] },
      { moduleNumber: 3, title: 'React Basics & Advanced React', hours: 26, topics: ['JSX', 'Custom Hooks', 'Context API'] },
      { moduleNumber: 4, title: 'UX/UI Principles & Capstone Project', hours: 24, topics: ['Figma Prototyping', 'Portfolio Application', 'Interview Prep'] }
    ]
  }
];
